// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Prefix from "./Prefix.res.js";
import * as Belt_Array from "@rescript/runtime/lib/es6/Belt_Array.js";
import * as Belt_Option from "@rescript/runtime/lib/es6/Belt_Option.js";

function levelToValue(level) {
  switch (level) {
    case "VERBOSE" :
      return 1;
    case "DEBUG" :
      return 2;
    case "INFO" :
      return 3;
    case "WARN" :
      return 4;
    case "ERROR" :
      return 5;
    case "TRACE" :
      return 6;
  }
}

function levelFromString(str) {
  let match = str.toUpperCase();
  switch (match) {
    case "DEBUG" :
      return "DEBUG";
    case "ERROR" :
      return "ERROR";
    case "INFO" :
      return "INFO";
    case "TRACE" :
      return "TRACE";
    case "VERBOSE" :
      return "VERBOSE";
    case "WARN" :
      return "WARN";
    default:
      return;
  }
}

function levelToString(level) {
  switch (level) {
    case "VERBOSE" :
      return "VERBOSE";
    case "DEBUG" :
      return "DEBUG";
    case "INFO" :
      return "INFO";
    case "WARN" :
      return "WARN";
    case "ERROR" :
      return "ERROR";
    case "TRACE" :
      return "TRACE";
  }
}

let globalLogLevel = {
  contents: undefined
};

function getEffectiveLevel(loggerLevel) {
  let globalLevel = globalLogLevel.contents;
  if (globalLevel !== undefined) {
    return globalLevel;
  } else {
    return loggerLevel;
  }
}

function _log(logger, typeLevel, msg) {
  let effectiveLoggerLevel = getEffectiveLevel(logger.level);
  if (levelToValue(typeLevel) < levelToValue(effectiveLoggerLevel)) {
    return;
  }
  let logFn;
  switch (typeLevel) {
    case "WARN" :
      logFn = prim => {
        console.warn(...prim);
      };
      break;
    case "ERROR" :
      logFn = prim => {
        console.error(...prim);
      };
      break;
    default:
      logFn = prim => {
        console.log(...prim);
      };
  }
  let prefix = Prefix.prefixFn(levelToString(typeLevel), logger.name);
  let isNullish = (msg == null || msg == undefined);
  if (isNullish) {
    let label = (msg === undefined ? 'undefined' : 'null');
    return logFn([
      prefix,
      label
    ]);
  }
  let _n = msg.length;
  if (_n !== 0) {
    if (_n !== 1) {
      return logFn([prefix].concat(msg));
    } else {
      return logFn([
        prefix,
        Belt_Array.getExn(msg, 0)
      ]);
    }
  } else {
    return logFn([prefix]);
  }
}

function make(name, levelOpt, param) {
  let level = levelOpt !== undefined ? levelOpt : "DEBUG";
  return {
    name: name,
    level: Belt_Option.getWithDefault(levelFromString(level), "DEBUG")
  };
}

function log(logger, msg) {
  _log(logger, "INFO", msg);
}

function info(logger, msg) {
  _log(logger, "INFO", msg);
}

function warn(logger, msg) {
  _log(logger, "WARN", msg);
}

function error(logger, msg) {
  _log(logger, "ERROR", msg);
}

function debug(logger, msg) {
  _log(logger, "DEBUG", msg);
}

function verbose(logger, msg) {
  _log(logger, "VERBOSE", msg);
}

function trace(logger, msg) {
  _log(logger, "TRACE", msg);
}

let ConsoleLoggerInternal = {
  make: make,
  log: log,
  info: info,
  warn: warn,
  error: error,
  debug: debug,
  verbose: verbose,
  trace: trace
};

function make$1(name, levelOpt, param) {
  let level = levelOpt !== undefined ? levelOpt : "DEBUG";
  return make(name, level, undefined);
}

function info$1(msg) {
  let defaultLogger = make$1("info", "VERBOSE", undefined);
  _log(defaultLogger, "INFO", msg);
}

function warn$1(msg) {
  let defaultLogger = make$1("warn", "VERBOSE", undefined);
  _log(defaultLogger, "WARN", msg);
}

function error$1(msg) {
  let defaultLogger = make$1("error", "VERBOSE", undefined);
  _log(defaultLogger, "ERROR", msg);
}

function debug$1(msg) {
  let defaultLogger = make$1("debug", "VERBOSE", undefined);
  _log(defaultLogger, "DEBUG", msg);
}

function verbose$1(msg) {
  let defaultLogger = make$1("verbose", "VERBOSE", undefined);
  _log(defaultLogger, "VERBOSE", msg);
}

function log$1(msg) {
  let defaultLogger = make$1("log", "VERBOSE", undefined);
  _log(defaultLogger, "INFO", msg);
}

function trace$1(msg) {
  let defaultLogger = make$1("trace", "VERBOSE", undefined);
  _log(defaultLogger, "TRACE", msg);
}

export {
  levelToValue,
  levelFromString,
  levelToString,
  ConsoleLoggerInternal,
  make$1 as make,
  info$1 as info,
  warn$1 as warn,
  error$1 as error,
  debug$1 as debug,
  verbose$1 as verbose,
  log$1 as log,
  trace$1 as trace,
}
/* No side effect */
